### ISSUE TITLE
Dashboards with Bokeh-Server

### ISSUE THREAD

**Issue by chdoig** [memex-explorer/memex-explorer#127]
I believe there are some issues when the autoload_server_tag gets corrupted in some way or for some reason the autoload_server_tag stored in the db is not in bokeh-server. 

Also, we should really evaluate if bokeh-server is ready for a deployment application and is able to scale to the number of plots we are going to deal with. There haven't been many stress tests on the bokeh-server.

An alternative could be to use just Bokeh without the server and reload the plots or store the script and div from components in the db.

Solutions:

Immediate:
- Change away from bokeh-server to generating new plots on reload by using bokeh components (script and div). 

Long-term bokeh-server implementation detail:
- Adding a query on the bokeh-server to assess if autoload_tag exists in the bokeh-server:
https://github.com/ContinuumIO/memex-explorer/blob/b1d80420c277e4350c6b0ccb7e0900451c5ba0a0/app/views.py#L308-L310

cc: @kdodia

**Comment by brittainhard** [comment]
We have moved away from using bokeh server to deliver plots.
