### ISSUE TITLE
Add ability to set different Nutch crawl configurations

### ISSUE THREAD

**Issue by chdoig** [memex-explorer/memex-explorer#128]
Nutch crawl configuration set to default and number_of_rounds set to two in all crawls:

https://github.com/ContinuumIO/memex-explorer/blob/master/app/crawls.py#L47

- [ ] Change default number of rounds to one.
- [ ] Write nutchpy script to use a continuously running loop that is interruptible with an API call.
- [ ] Nutch crawl script could be able to select the folder with the configuration to use.

Open separate issue tasks: #134, #135, #136

**Comment by brittainhard** [comment]
Still relevant?
