### ISSUE TITLE
Handling different configuration in crawls (ACHE and Nutch)

### ISSUE THREAD

**Issue by chdoig** [memex-explorer/memex-explorer#138]
Short-term:
- [x] Use default configuration for crawlers and remove all configuration fields from forms #137

Long-term:
- [ ] UI/UX around different configuration mechanisms

**Comment by brittainhard** [comment]
This has to be done in order for Ache crawls to be run alongside eachother. Not sure if the UI/UX stuff is still relevant.

**Comment by brittainhard** [comment]
Right now ache is set up to allow different configs for each crawl, but I'm not sure whether it's still important to be able for a user to change these configs.

**Comment by brittainhard** [comment]
No longer necessary.
