### ISSUE TITLE
Discuss crawl actions

### ISSUE THREAD

**Issue by kdodia** [memex-explorer/memex-explorer#162]
Currently Nutch and ACHE have different modes of operation:

**Nutch**
Proceeds in "rounds", where a natural stopping point (polite stop) can be requested at the end of each round.

**ACHE**
Long-running, cannot be paused.

Proposed actions:
 - **Restart**
    - Start crawl over from initial settings (needs clarification)
 - **Start**
    - Either resume an existing crawl instance *(Nutch only)*, or begin a new crawl
 - **Pause** *(Nutch only)*
    - Stop crawl at the end of the next round
 - **Terminate**
    - Force halt current crawl (needs clarification)

**Comment by brittainhard** [comment]
No longer relevant to the Django app.
