### ISSUE TITLE
Feed ache relevant pages to nutch

### ISSUE THREAD

**Issue by aterrel** [memex-explorer/memex-explorer#175]
- [ ] Create a hybrid crawler names "ache-nutch"
- [ ] Make the crawler starts a ache model and starts producing relevant pages from its seed list
- [ ] Create a poller that then starts nutch as ache's relevant pages are found. Each round of nutch finishing should grab the latest seeded relevant pages from Nutch.
- [ ] Have the nutch crawl dump images to the given image space.

**Comment by brittainhard** [comment]
Currently you can get the relevant seeds list from ache. Is this enough?

**Comment by ahmadia** [comment]
Not sure if this is still a target for development.

**Comment by brittainhard** [comment]
Going to close this. This is no longer anywhere on our development timeline, and is no longer really viable or useful, given that we already have a way to feed seeds from ache into nutch, using the "download relevant pages" button.
