### ISSUE TITLE
413 Entity Too Large Error when feature and model classifier files are added

### ISSUE THREAD

**Issue by sarahjoannareed** [memex-explorer/memex-explorer#402]
When I add the pageclassifier.models file to Model in Memex Explorer for Model and the the pageclassifier.features file to Features in Memex Explorer I get a 413 Entity Too Larger Error
413 Request Entity Too Large

nginx/1.4.6 (Ubuntu)

**Comment by brittainhard** [comment]
Fixed by changing nginx conf.
