### ISSUE TITLE
Home Page buttons don't work

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/memex-explorer#408]
Learn More, Documentation, and Image Space don't go anywhere.

http://explorer.continuum.io/ for pilot demo.

**Comment by brittainhard** [comment]
@wmburke currently adding some tests for this. I'll let you know as soon as them are integrated into the deployed application.

**Comment by wmburke** [comment]
Okay - I see that these work in Chrome also, but not in firefox. In Firefox, clicking on these buttons does nothing.

**Comment by brittainhard** [comment]
Ahh i see now. Thanks for clearing that up. I'm experiencing the same problems in firefox, also with the buttons. Thanks for catching that.

**Comment by brittainhard** [comment]
Fixed in #415
