### ISSUE TITLE
Double Image Space links

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/memex-explorer#409]
There are currently two Image Space links from the home page. One in the upper right corner and one next to the Documentation button. Not sure if these are intended to be v1 and v2 or what.

http://explorer.continuum.io/ for pilot demo.

**Comment by wmburke** [comment]
It's possible that it's just not working yet, but I don't see how to get to Image Space v1 as of yet. I can clarify why there are two when I send the demo for review, but it needs to be obvious how to get to each of them.

**Comment by brittainhard** [comment]
Fixed in #423
