### ISSUE TITLE
Buttons don't show up on crawl page

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/memex-explorer#410]
Eg, http://explorer.continuum.io/projects/foo/crawls/foooooooo/

**Comment by brittainhard** [comment]
@wmburke this one is difficult for me to diagnose. Which buttons are missing, exactly? Are you looking for the "Goto Solr" and "Dump Images" buttons? If that is the case, they are not available for ache crawls. I am currently working on documentation to explain these differences between Nutch and Ache.

**Comment by wmburke** [comment]
Hopefully this helps - it's the settings, stop, and start icons.
![missing crawl icons](https://cloud.githubusercontent.com/assets/121620/6804863/67b4c6da-d216-11e4-8a80-70841044ec1a.png)

if it makes a difference, I'm using firefox 36.0.4 on Ubuntu 14.04

**Comment by wmburke** [comment]
Interesting. I just double checked this in Chrome and it shows up fine. I have forced a refresh multiple times, but the problem persists. Sorry I can't check it anywhere else.

**Comment by brittainhard** [comment]
So i'm getting somewhere with this one. Seems like they are only failing to show up on the crawl page itself.

**Comment by brittainhard** [comment]
@wmburke this has been fixed in #415 . Will show up on the deployed server very soon.

**Comment by wmburke** [comment]
Ok. Let me know when it shows up.

**Comment by brittainhard** [comment]
This has been fixed in #415
