### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/memex-explorer#412]
I have added some descriptions to the sample projects that are in there, although I don't think it's enough. Can we run some sample crawls and leave them for them to investigate?

I'm thinking one project for an ACHE crawl with a description that makes it clear what it is plus a similar one for a Nutch crawl.

Is this possible?

Thank you,
Wayne

**Comment by brittainhard** [comment]
Yes I can add this in.

**Comment by brittainhard** [comment]
This will be done by Katrina.
