### ISSUE TITLE
elasticsearch to kibana pipeline

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#445]
1) User creates new project and file-uploads a zip file with a bunch of PDFs in a zip file. Create a tika container, elasticsearch container, and kibana container 
2) Start up the tika container, feed these to it, and take the json results.
3) Feed the json results to elasticsearch.
4) The elasticsearch container exposes a port and kibana queries that port.
5) kibana exposes a port that nginx proxies to a url

**Comment by brittainhard** [comment]
closed in #451
