### ISSUE TITLE
AWS setup script

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#446]
write a script to setup an aws machine with:
- nginx installed
- memex-explorer source downloaded
- dockerfiles in standard locations
- docker-compose and nignx templates in standard locations

**Comment by amfarrell** [comment]
@quasiben Can you give me credentials for spinning up AWS machines?

**Comment by quasiben** [comment]
Sent a message to the key holders

**Comment by brittainhard** [comment]
Dealt with in #454
