### ISSUE TITLE
Integrate Facet Space

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#487]

**Comment by amfarrell** [comment]
What actually is facet space and where is the codebase?

**Comment by brittainhard** [comment]
That's an excellent question @amfarrell. I don't have a clear idea. A version of it exists here: https://github.com/ContinuumIO/facetview-gcis/tree/chdoig . I think Andy said something about it not being a totally up-to-date version. I think that you should get in touch with him about what version of the code we should be using and where it is.

**Comment by brittainhard** [comment]
No longer useful. We decided to go with Kibana for interacting with Elasticsearch.
