### ISSUE TITLE
VM created by vagrant file should start up gunicorn

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#496]
currently, https://github.com/memex-explorer/memex-explorer/blob/master/deploy/deploy_vagrant.sh seems to be missing several commands needed to run the django application under gunicorn:

[] echo 'CONFIG SET dir /tmp/some/directory/other/than/var' | redis-cli
[] echo 'CONFIG SET dbfilename temp.rdb' | redis-cli
[] manage.py migrate
[] manage.py collectstatic
[] running a gunicorn script. such as https://github.com/memex-explorer/memex-explorer/blob/master/deploy/gunicorn_start.sh

**Comment by ahmadia** [comment]
I broke this out in the vagrantfile to separate build from run.

**Comment by ahmadia** [comment]
@amfarrell @brittainhard - Can one of you explain to me what the purpose of the gunicorn scripts in Memex Explorer is?

I don't see gunicorn references anywhere in the source.  I only see it started.  The way I'm currently starting the server is like this:

```
  /home/vagrant/miniconda/envs/memex/bin/python ./manage.py runserver 0.0.0.0:8000
```

**Comment by ahmadia** [comment]
reping @amfarrell @brittainhard

**Comment by ahmadia** [comment]
I think Brittain mentioned something about gunicorn managing the Django server.  Would we prefer to have gunicorn managing it?
