### ISSUE TITLE
Smarter Docker + Vagrantfile caching

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#503]
@amfarrell - after digging around on the documentation for Vagrant, it looks like caching Docker images will be a non-trivial endeavor.  The best solution I found is this:

https://github.com/fgrehm/vagrant-cachier/issues/131

Basically, we can't map the Docker cache to a synchronized directory on the host directory.  The best solution is to manually save and load Docker images manually.  I think I can automate this in the Vagrant script, but I may not get to it tonight.

**Comment by amfarrell** [comment]
How frequently are users going to be spinning up new vagrant boxes? If they are only installing the system locally and running salt highstate once, how impactful is this issue?

**Comment by ahmadia** [comment]
This is a developer, not a user issue. It's not priority.

**Comment by ahmadia** [comment]
This isn't really an issue anymore as Docker is no longer part of the development build.
