### ISSUE TITLE
If Celery already running, can't just use it.  Fails.

### ISSUE THREAD

**Issue by BrianWilson1** [memex-explorer/memex-explorer#513]
[INFO    ] Executing command '/home/vagrant/miniconda/envs/memex/bin/celery --detach --workdir="/vagrant/source" -A memex worker' as user 'vagrant' in directory '/vagrant/source'
[DEBUG   ] stderr: ERROR: Pidfile (celeryd.pid) already exists.
Seems we're already running? (pid: 8448)
[INFO    ] {'pid': 8970, 'retcode': 0, 'stderr': "ERROR: Pidfile (celeryd.pid) already exists.\nSeems we're already running? (pid: 8448)", 'stdout': ''}
[INFO    ] Completed state [/home/vagrant/miniconda/envs/memex/bin/celery --detach --workdir="/vagrant/source" -A memex worker] at time 19:02:07.775293

**Comment by ahmadia** [comment]
I'll take this one.

**Comment by ahmadia** [comment]
We got this one!
