### ISSUE TITLE
Example model seeds and cats file

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#520]
In order for people to get up and running with Memex explorer, we need to show them how to run a Nutch/ACHE job, which means we need example files in the repository.

**Comment by ahmadia** [comment]
@kriehl - I'm putting this one to you to either assign or do.

**Comment by kriehl** [comment]
This is a much lower priority than other issues that have yet to be addressed.  I'm pushing it off.

**Comment by ahmadia** [comment]
We can't verify the behavior of the dashboard without some mockup data. I
think Brittain has an example model and seeds list he's been using that we
need to commit to the repository.

**Comment by ahmadia** [comment]
I still think we should have this in our repository and documented :)

**Comment by brittainhard** [comment]
Working on this.

**Comment by brittainhard** [comment]
So apparently the sample model files were already in the repo. Going to add the sample seeds file that goes along with the model.
