### ISSUE TITLE
Setting Up Log.io

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#522]
```
npm install -g log.io
```
Open the harvester config, change the settings to watch the Nutch file. 
```
vim ~/.log.io/harvester.conf
```
Change the settings to the following:
```
exports.config = {
  nodeName: "application_server",
  logStreams: {
    nutch: [
      "/<anaconda_location>/envs/<environment_name>/lib/nutch/logs/hadoop.log"
    ]
  },
  server: {
    host: '0.0.0.0',
    port: 28777
  }
}
```
Start the server by running:
```
log.io-server
```
Start the harvester by running:
```
log.io-harvester
```

**Comment by brittainhard** [comment]
@ahmadia

**Comment by ahmadia** [comment]
Awesome, I can take it from here.

**Comment by ahmadia** [comment]
cc @amfarrell

**Comment by brittainhard** [comment]
In case `log.io-server` or `log.io-harvester` commands are not set to path, then you can run them from the folder where they are located on the system.

**Comment by ahmadia** [comment]
Okay, I'm going to get this working today.

**Comment by ahmadia** [comment]
Fixed in https://github.com/memex-explorer/memex-explorer/pull/539, modulo ElasticSearch container support.
