### ISSUE TITLE
Lock down a Docker version

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#535]
Right now we're picking up the Docker from the system (1.0.1 on Ubuntu, 1.5 on Brittain's dev machine).  We should use a consistent Docker/Docker-compose.

**Comment by ahmadia** [comment]
This is a very general SLS repo that can handle any version of Docker dependencies:
https://github.com/saltstack-formulas/docker-formula/blob/master/docker/init.sls

**Comment by ahmadia** [comment]
@amfarrell - can you make the call/guess on whether we should stick to 1.0.1 or upgrade to 1.5?  I would try 1.0.1 and see if it works/has all the features we need.  That means downgrading the installed docker-compose (use pip the way we install docker-py) to a matching version.  If that doesn't work, we should go up to 1.5 and install manually, by hardcoded commands for now if needbe.

**Comment by amfarrell** [comment]
We are no longer using docker-compose.
- We were using it to spin up containers for kibana/elasticsearch/tika when each project was created. We are no longer doing that but instead are creating only 3 containers on system startup
- We were using docker-compose to create those three containers. We are now only using salt for that.

**Comment by ahmadia** [comment]
1.0.1 it is. Feel free to close.

**Comment by ahmadia** [comment]
We recently experienced problems interoperating with CMU's TAD project due to our Docker version being out of date.  I think we should upgrade to Docker version 1.7.0.

Note that this task is not immediately straightforward.  I needed to uninstall the system Docker, then set the following configuration options in `/etc/default/docker`

```
# Docker Upstart and SysVinit configuration file

# Customize location of Docker binary (especially for development testing).
#DOCKER="/usr/local/bin/docker"

DOCKER_OPTS="-s aufs"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"
```

**Comment by ahmadia** [comment]
cc: @amfarrell @brittainhard.

**Comment by ahmadia** [comment]
Any objections?  I'll put together a branch this week after the DDT demo.

**Comment by amfarrell** [comment]
I am in favor of being on one particular docker version and 1.7 seems fine.

**Comment by ahmadia** [comment]
See: https://github.com/memex-explorer/memex-explorer/commit/6d5ca8665384e593a5a821a98e90b39828451e91

**Comment by ahmadia** [comment]
Not locked to a specific Docker version, but we could try hardcoding it.

**Comment by brittainhard** [comment]
@ahmadia whats the relevance of this issue?

**Comment by ahmadia** [comment]
Close. We use 1.7

On Monday, August 10, 2015, Brittain Hard <notifications@github.com> wrote:

> @ahmadia <https://github.com/ahmadia> whats the relevance of this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/535#issuecomment-129575916>
> .
>


-- 
_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>
