### ISSUE TITLE
Seed list URLs aren't accepted by URL filters

### ISSUE THREAD

**Issue by chrismattmann** [memex-explorer/memex-explorer#540]
Steps to reproduce

1. Create new Project ATF crawl Description ATF crawl
2. Add new Crawl, select Nutch
3. Provide following seeds.txt file
```
[chipotle:DARPA/DARPA Memex/ATF] mattmann% more seeds.txt 
classifieds.al.com
[chipotle:DARPA/DARPA Memex/ATF] mattmann% 
```
4. Start crawl
5. Observe following in logs:
```
nutch application_server 2015-05-27 12:50:01,037 INFO crawl.Injector - Injector: Total number of urls rejected by filters: 1
```
Apparently the regex-urlfilter isn't getting set up correctly for the injected seed URLs.

**Comment by chrismattmann** [comment]
OK I think I will update crawl_tasks.py, and make it so when the seeds.txt is uploaded that we overwrite the regex-urlfilter here:

```
vagrant@vagrant-ubuntu-trusty-64:~/miniconda/envs/memex$ cd /home/vagrant/miniconda/envs/memex/lib/nutch
vagrant@vagrant-ubuntu-trusty-64:~/miniconda/envs/memex/lib/nutch$ ls
bin  conf  lib  logs  plugins
vagrant@vagrant-ubuntu-trusty-64:~/miniconda/envs/memex/lib/nutch$ cd conf
vagrant@vagrant-ubuntu-trusty-64:~/miniconda/envs/memex/lib/nutch/conf$ ls
adaptive-mimetypes.txt         domain-suffixes.xml   host-urlnormalizer.txt  nutch-conf.xsl     parse-plugins.xml     schema-solr4.xml       suffix-urlfilter.txt
automaton-urlfilter.txt        domain-suffixes.xsd   httpclient-auth.xml     nutch-default.xml  prefix-urlfilter.txt  schema.xml
configuration.xsl              domain-urlfilter.txt  log4j.properties        nutch-site.xml     regex-normalize.xml   solrindex-mapping.xml
domainblacklist-urlfilter.txt  elasticsearch.conf    mimetype-filter.txt     parse-plugins.dtd  regex-urlfilter.txt   subcollections.xml
vagrant@vagrant-ubuntu-trusty-64:~/miniconda/envs/memex/lib/nutch/conf$ pwd
/home/vagrant/miniconda/envs/memex/lib/nutch/conf
vagrant@vagrant-ubuntu-trusty-64:~/miniconda/envs/memex/lib/nutch/conf$ 
```

**Comment by chrismattmann** [comment]
@brittainhard @ahmadia  FYI

**Comment by chrismattmann** [comment]
FYI too, this makes Nutch pretty much useless, so priority is critical on this.

**Comment by ahmadia** [comment]
Note: Seeds must be of the form `http://xxx`, neglecting the protocol tag apparently breaks the Nutch regex filter.  Should we write an ingest script that fixes URLs that are not of the appropriate form?

**Comment by chrismattmann** [comment]
yeah we should validate the URLs. At the same time it may also be useful to only enable those seed domains with the regex-urlfilter instead of enabling everything.

**Comment by lewismc** [comment]
Ensuring that a protocol is pretended to any URL has always been a
prerequisite for the default url filter in Nutch.
Adding the flexible behavior to change this default is not a good idea imho
as there may be several protocols from which any Website may be fetched
from!
I think it is down to the client/user to ensure protocols accompany the
URLs

On Wednesday, May 27, 2015, Aron Ahmadia <notifications@github.com> wrote:

> Note: Seeds must be of the form http://xxx, neglecting the protocol tag
> apparently breaks the Nutch regex filter. Should we write an ingest script
> that fixes URLs that are not of the appropriate form?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/540#issuecomment-105910351>
> .
>


-- 
*Lewis*

**Comment by chrismattmann** [comment]
hey @lewismc i'm not proposing to make it so that we don't need a protocol. I'm proposing that in Memex Explorer:

1. We should validate seed URLs provided are _actual_ URLs that Nutch will like.
2. Currently memex-explorer's regex-urlfilter.txt accepts *all* domains. I think it should be specific to the specific provided seed domain URLs, and only allow those (for now) and later we should just expose editing the regex-urlfilter.txt file somehow through a form.

**Comment by lewismc** [comment]
Sounds good Chris

On Wednesday, May 27, 2015, Chris Mattmann <notifications@github.com> wrote:

> hey @lewismc <https://github.com/lewismc> i'm not proposing to make it so
> that we don't need a protocol. I'm proposing that in Memex Explorer:
>
>    1. We should validate seed URLs provided are *actual* URLs that Nutch
>    will like.
>    2. Currently memex-explorer's regex-urlfilter.txt accepts *all*
>    domains. I think it should be specific to the specific provided seed domain
>    URLs, and only allow those (for now) and later we should just expose
>    editing the regex-urlfilter.txt file somehow through a form.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/540#issuecomment-105915339>
> .
>


-- 
*Lewis*

**Comment by ahmadia** [comment]
I'm removing the bug label and setting this as a feature.

**Comment by ahmadia** [comment]
And a big +1 to this.  I don't think it's actually that hard to expose a form here to allow a custom regex-urlfilter, but it should be optional and prepopulated with the default '*'.  It might also be useful to have a button that says "restrict crawl to seed domains".

**Comment by chrismattmann** [comment]
@nipurnishere @shivikathapar please have a look at this too.

**Comment by nipunhere** [comment]
Shivika and I tried some frontend validation snippet and we think something like this could be implemented on the frontend where urls from the seed file could be taken into an array in javascript and checked for validity. We setup a jsbin to demo that - http://jsbin.com/sefeli/7/edit?html,js,output

**Comment by shivikathapar** [comment]
Here is what could be another solution. You can upload a seed file or enter multiple domains in the text box provided( a new domain in a new line). The code checks for valid URLs in the seed list; when found, it checks further for protocol's presence in the URL - if not found, it prefixes it with http:// as default.

Here is a link to the code:  https://jsfiddle.net/shivikathapar/bpepqnjw/

**Comment by lewismc** [comment]
Did you guys see the jquery url validation logic I sent you both? I sent it
to your JPL email addresses.


On Thursday, May 28, 2015, shivikathapar <notifications@github.com> wrote:

> Here is what could be another solution. You can upload a seed file or
> enter multiple domains in the text box provided( a new domain in a new
> line). The code checks for valid URLs in the seed list; when found, it
> checks further for protocol's presence in the URL - if not found, it
> prefixes it with http:// as default.
>
> Here is a link to the code: https://jsfiddle.net/shivikathapar/bpepqnjw/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/540#issuecomment-106621447>
> .
>


-- 
*Lewis*

**Comment by nipunhere** [comment]
@lewismc, Yes, we saw the plugin. What we understood from comments on top and discussion with you is that currently Nutch breaks if the url doesn't have a protocol. The plugin on - http://jqueryvalidation.org/url-method also states a url to be invalid if it does not contain the protocol. 

In the snippet that we prepared, we first check if all urls in the seed have a protocol prefixed to them or not. If not found, it appends the most common protocol ( http://) in front of each of the urls. Then it performs a checks for url format validity. The plugin does not do that.

**Comment by chrismattmann** [comment]
Awesome please test @nipunhere @shivikathapar and pull request cc @lewismc

**Comment by lewismc** [comment]
Dynamite
Pull request please and we can test

On Thursday, May 28, 2015, Chris Mattmann <notifications@github.com> wrote:

> Awesome please test @nipunhere <https://github.com/nipunhere>
> @shivikathapar <https://github.com/shivikathapar> and pull request cc
> @lewismc <https://github.com/lewismc>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/540#issuecomment-106631388>
> .
>


-- 
*Lewis*

**Comment by ahmadia** [comment]
Folks let's make sure we build off the work done in here: https://github.com/memex-explorer/memex-explorer/pull/553

**Comment by lewismc** [comment]
@ahmadia there is absolutely no issue description on #553 I have no idea what this issue is about.

**Comment by ahmadia** [comment]
@lewismc - it's a pull request, tying up problems in #552.  You can read the commit logs or look at the files changed to see what work was done.

**Comment by ahmadia** [comment]
The changed code is visible here: https://github.com/memex-explorer/memex-explorer/pull/553/files

**Comment by lewismc** [comment]
I understand it's a pull request :+1: thanks for making that blatantly obvious ;)
Thanks for the references

**Comment by ahmadia** [comment]
Where are we on this?  @chrismattmann - do you still want this assigned to you?

**Comment by chrismattmann** [comment]
go ahead and re-assign haven't had any time for this @ahmadia
