### ISSUE TITLE
Vagrant VM Memory Size

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#542]
While running some memory-intensive command (conda install, nutch crawl, etc), suddenly my VM became unresponsive and died.  What gives?

**Comment by ahmadia** [comment]
Odds are your VM ran out of memory.  We should document this in a troubleshooting section.  Is 4 GB a reasonable VM size?

**Comment by ahmadia** [comment]
cc @chrismattmann @amfarrell

**Comment by chrismattmann** [comment]
yep, had to update from 4GB to 6GB in the Vagrantfile:

```
[chipotle:~/git/memex-explorer] mattmann% git diff
diff --git a/Vagrantfile b/Vagrantfile
index aa2b116..6022aea 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -55,7 +55,7 @@ Vagrant.configure(2) do |config|
   #   vb.gui = true
   #
   #   # Customize the amount of memory on the VM:
-    vb.memory = "4096"
+    vb.memory = "6144"
   end
   #
   # View the documentation for the provider you are using for more
[chipotle:~/git/memex-explorer] mattmann% 
```

**Comment by ahmadia** [comment]
we're going to maybe turn a couple more cpu cores on as well.  cc @brittainhard

**Comment by ahmadia** [comment]
@brittainhard @aterrel @chrismattmann @kriehl - Any objections to making the virtual machine 8 GB in size?  Anybody have a laptop with less than 16 GB of memory?

**Comment by ahmadia** [comment]
cc @amfarrell

**Comment by amfarrell** [comment]
That seems like a good idea to me.

**Comment by chrismattmann** [comment]
8GB fine with me.

**Comment by brittainhard** [comment]
So I recently had an issue with this when I tried to install the vagrant machine on my Macbook Air, which only had 4GB memory. I suspect that there may also be other people with memory below 8GB, so I'm wondering if we shouldnt go back to 2GB memory allocated for the Vagrant VM, @ahmadia.

**Comment by ahmadia** [comment]
6 GB for the Vagrant VM, this isn't worth messing around with any more.
