### ISSUE TITLE
Fix vagrant provision not working on first go

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#549]
It looks like Salt is having issues setting a file permission after copy but this goes away the second time.

**Comment by ahmadia** [comment]
One thing to check is if you call "vagrant provision" after a "vagrant reload", you may need to restart docker.io with:

```
sudo stop docker.io
sudo start docker.io
```

**Comment by brittainhard** [comment]
@ahmadia how relevant is this issue now?

**Comment by ahmadia** [comment]
Not an issue.
