### ISSUE TITLE
Integrate Gulp and Browserify

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#554]
[Browserify](http://browserify.org/) is a javascript utility that allows you to write JavaScript using modules. It works by compiling all of your javascript into a single file. [Gulp](https://github.com/gulpjs/gulp) is an automated build process which will automatically compile the javascript code. Integration of both these utilities will make a big difference in terms of creating code readability and reduction of code complexity.

I already have working versions of both these utilities on my personal repositories, so integrating them should be simple. The difficult part will be ensuring that salt correctly installs these utilities and builds the javascript.

**Comment by brittainhard** [comment]
This will also allow for the integration of javascript automated unit testing.

**Comment by brittainhard** [comment]
I think that the package.json and gulpfile here will do most of what we need it to do: https://github.com/brittainhard/fuzzyjson

**Comment by chrismattmann** [comment]
Hi @brittainhard - what benefit will this provide us other than code readability. I've never used this tool and I'm weary of introducing things that make it so that folks like me can't contribute here or there. I'd like to know more about why we should be spending time on this, rather than adding new features. Thanks for listening and for letting me know.

**Comment by brittainhard** [comment]
@chrismattmann I think you bring up some good points. The use of Gulp and Browserify is not all that mainstream, and most people who have written javascript code don't have and knowledge of these tools. There is also a conceptual hurdle to overcome when using these tools. I think that in my situation, because of my familiarity with the tools, that the benefits far outweigh the technical debt that we might incur.

I should point out that the use of these tools does not put constraints on any other javascript development. Javascript files can still be loaded as static files apart from the build process, and only a trivial amount of knowledge of Django and the DOM is required to include new javascript staticfiles in the templates. 

The use of Gulp and Browserify would greatly improve my development process. It would allow me to easily add new dependencies and makes the managing of static files trivial, since it compiles the selected files into one file. It would also allow me to write with modules, and I don't think I could overstate the benefits of this. 

I will certainly take your points into consideration though before I start working on this feature.

**Comment by brittainhard** [comment]
Closing this. I think that the difficulties outweigh the benifits.
