### ISSUE TITLE
Log.io Files Missing

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#555]
log.io-server fails to run because it is missing required files that arent being generated by the install. Salt can create these files for us.

**Comment by chrismattmann** [comment]
Hmm, I am not seeing this @brittainhard - log.io seems to work fine for me. Can you let me know what files you are talking about?

**Comment by ahmadia** [comment]
@chrismattmann - I hotfixed this on your laptop with the "sudo npm install -g log.io" command.  It's reasonable for us to manage these files anyway so I'm +1 on doing this, even if it's hard for us to reproduce.

**Comment by chrismattmann** [comment]
Got it

**Comment by brittainhard** [comment]
@ahmadia If installing that way works, why aren't we doing it in the saltfile?

**Comment by ahmadia** [comment]
I think this may need to be run "as the user vagrant" in order to work:

https://github.com/memex-explorer/memex-explorer/blob/master/salt/roots/salt/logio.sls#L10

**Comment by ahmadia** [comment]
@brittainhard - #556 might be a fix.  Like I said, it's not a bad idea for us to be managing the configuration files from Salt, so I'm okay with your approach as well.

**Comment by brittainhard** [comment]
Log.io seems to be working fine on vagrant without issues. Closing this.
