### ISSUE TITLE
Need script for installing and running on AWS

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#559]
Currently, the procedure for installing memex explorer on AWS is as follows:

cd memex-explorer/deploy
    maybe first 
    conda env create --file ./deploy_environment.yml
source activate memex_deploy
GIT_BRANCH='master' AWS_ID='XXX' AWS_SECRET='XXX' python ./ec2-fabfile.py quitafterec2setup
ssh -i ./latest.pem ubuntu@IP_ADDR_OF_CREATED_MACHINE

#now on the remote machine

sudo adduser vagrant
sudo adduser vagrant sudo
sudo passwd -d vagrant
sudo visudo
    make sure there is a line that says
    sudo ALL=(ALL) NOPASSWD:ALL
sudo su vagrant
cd ~
mkdir resources
sudo add-apt-repository ppa:saltstack/salt
sudo apt-get update
sudo apt-get install git salt-master salt-minion salt-syndic
git clone https://github.com/memex-explorer/memex-explorer
sudo cp -r memex-explorer /vagrant
cd /vagrant
sudo chown -R vagrant:vagrant .
sudo find . -type f -name '*' -print0 | sudo xargs -0 chown vagrant:vagrant
sudo mkdir /etc/salt
sudo ln -s /vagrant/salt/minion /etc/salt/minion
sudo ln -s /vagrant/salt/roots/salt /srv/salt
sudo /usr/bin/salt-call state.highstate --retcode-passthrough --log-level=debug
  
  copy over nginx config
  copy over htpassword to /etc/nginx/.htpasswd
  reload nginx
  
sudo screen -S memex-explorer
su vagrant
cd source
start gunicorn by running /vagrant/deploy/gunicorn_start.sh

The ec2 fabfile needs to be rewritten to reflect this.

**Comment by ahmadia** [comment]
@amfarrell aren't there a couple of hardcoded endpoint locations for Kibana on a non-master branch to deal with as well?

**Comment by amfarrell** [comment]
Good catch. the `git clone` command should be followed by a `git checkout ec2-deployed` It is worth noting that those hardcoded endpoints point to explorer.continuum.io

**Comment by ahmadia** [comment]
Right.  I think the hardcoded information needs to be lifted in variables stored in a `settings.py` file or similar before we can close this issue.  I'm fine with a "explorer.continuum.io_settings.py" or similar committed to the repository that we can manage through documented shell comands.

**Comment by amfarrell** [comment]
This script now exists at https://github.com/memex-explorer/memex-explorer/blob/amfarrell/create-ec2/deploy/ec2-fabfile.py

**Comment by ahmadia** [comment]
Is there an active Pull Request?  Does the script need review/testing or is that branch ready to merge?

**Comment by amfarrell** [comment]
There was a pull request that was merged. Unfortunately, it did not reference this issue.
