### ISSUE TITLE
Projects dropdown in header does not work on a Project's Page

### ISSUE THREAD

**Issue by shivikathapar** [memex-explorer/memex-explorer#564]
This issue is faced in Chrome Version 43.0.2357.81. I am running OS X Version 10.10.2.

Steps to reproduce this issue:
1. Click on any project in Memex Explorer.
2. After arriving on this project's page, click on "Projects" dropdown at the top right on the screen.

The dropdown menu does not appear.

![screen shot 2015-06-03 at 12 39 21 pm](https://cloud.githubusercontent.com/assets/3753781/7969704/98e77806-09ed-11e5-8315-ba284c67b46a.png)

**Comment by brittainhard** [comment]
@shivikathapar i appreciate all these found bugs. I'm currently working on other tasks right now but I will get to them soon.

**Comment by ahmadia** [comment]
Great work @shivikathapar!

**Comment by brittainhard** [comment]
Was unable to verify this bug.

**Comment by shivikathapar** [comment]
Hey @brittainhard, yes looks like its working now! Thanks.

**Comment by brittainhard** [comment]
Aweome, thanks @shivikathapar
