### ISSUE TITLE
Ache needs nonzero exit codes

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#583]
ACHE does not give nonzero error codes. Therefore, celery currently reports all ended tasks as successful, regardless of their log output. Instead, it should 

preferably: grep the log or results for definitive indication of success and report error if it is absent
at least: grep the log for indications of error and report error if any are found.

**Comment by amfarrell** [comment]
The following error results from starting ACHE being run with the seeds list found at source/test_resources/test_crawl_data/cats.seeds and the model found in source/test_resources/test_model

**Comment by brittainhard** [comment]
Not sure if this should be added to the ACHE repo, since the problem is with ACHE and not memex explorer.

**Comment by ahmadia** [comment]
Yes, we should raise an issue there.

**Comment by amfarrell** [comment]
@brittainhard Could I please be un-assigned from this issue?
