### ISSUE TITLE
remove "Dump Images" button at /projects/<projectname>/crawls/<crawlname>/, which does nothing

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#584]
Clicking on the button causes a throbber to appear but does not produce an image dump. According to @brittainhard, it was agreed-upon earlier that we should remove it but this has not been implemented.

**Comment by brittainhard** [comment]
This needs to be talked about with the JPL team.

**Comment by brittainhard** [comment]
Keeping the dump images button for now.
