### ISSUE TITLE
Error when changing staticfiles on vagrant

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#593]
So I just found something interesting. I made some changes to a javascript file while developing on vagrant, and the next time it loaded it, it error'd out. Looking at it again, it looks as if all the code I had written  into the file had been thrown at the bottom of the file as a series of unreadable characters. Looks like this: 
```
  $("#dumpImages").on('click', function(){
    $("#nutchButtons").append('<i id="imageSpinner" class="fa fa-refresh fa-spin" style="font-size:20;"></i>')
    $.ajax({
      type: "POST",
      data: {"action": "dump"},
      success: function(response) {
        sweetAlert("Success", "Images have been successfully dumped!", "success");
        $("#imageSpinner").remove()
      },
      failure: function() {
        sweetAlert("Error", "Image dump has failed.", "error");
        $("#imageSpinner").remove()
      }
    });
  });


});
�������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
```

So the number of unreadable characters happens to be the exact number of characters that I had added to the code. Further tests with adding one new character confirms that these are indeed the new lines of code I had added.

**Comment by brittainhard** [comment]
This is an issue, but I'm not entirely sure whether it directly impacts the vagrant setup.

**Comment by amfarrell** [comment]
@brittainhard how consistently are you able to reproduce this? Or is it intermittent?

**Comment by brittainhard** [comment]
@amfarrell this is completely consistent as far as I can tell. I can show you how to reproduce it if necessary.

**Comment by brittainhard** [comment]
since we are no longer using vagrant this no longer applies.

**Comment by ahmadia** [comment]
We're actually still using Vagrant in some situations, but it's no longer the primary development platform.  For example, Vagrant is needed if you're standing up Docker containers from an OS X platform.

**Comment by ahmadia** [comment]
Let's leave this on the backlog if it's not affecting you though, Brittain.

**Comment by brittainhard** [comment]
Fair enough, but there is also a way of standing up docker containers using boot2docker.

**Comment by ahmadia** [comment]
I'm going to close this issue if it's not currently affecting anyone.  Please reopen if it is causing you grief.
