### ISSUE TITLE
ec2 creation should attach larger EBS

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#596]
the default EBS storage size attached to a new EC2 deploy is 7.8GB. This needs to be significantly larger (at least 32 GB) to hold the data from crawls in demos.

**Comment by amfarrell** [comment]
this suggestion does not appear to work: http://stackoverflow.com/questions/13585857/how-to-launch-ec2-instance-with-boto-specifying-size-of-ebs

**Comment by amfarrell** [comment]
This is stalled on being unable to run the following script

    import os
    import boto.ec2
    ec2 = boto.ec2.connect_to_region('us-east-1',
      aws_access_key_id = os.environ.get('AWS_ID'),
      aws_secret_access_key = os.environ.get('AWS_SECRET'))
    vol = ec2.create_volume(22, 'us-east-1a')


I get the following error:

boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
'<?xml version="1.0" encoding="UTF-8"?>\n<Response><Errors><Error><Code>VolumeLimitExceeded</Code><Message>Maximum number of active volumes bytes, 20, exceeded.</Message></Error></Errors><RequestID>80e3345a-0121-4b3d-9df2-fcbd76787b5a</RequestID></Response>'

**Comment by amfarrell** [comment]
current branch https://github.com/memex-explorer/memex-explorer/tree/amfarrell/auto-mount-other-EBS-volume

**Comment by ahmadia** [comment]
We're not currently focusing on automated deployments.
