### ISSUE TITLE
"submit" button for crawl creation fails on vagrant

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#597]
The user who is accessing vagrant at localhost:8000 gets sent to localhost instead.

**Comment by brittainhard** [comment]
I should note, this is for everything that involves get_success_url, not just crawls. So projects and crawl models as well.

**Comment by amfarrell** [comment]
Meaning the original issue was with everything involving get_success_url? Good. pull #600 fixes all of them.
