### ISSUE TITLE
migration.py stalls salt 

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#604]
[DEBUG   ] stdout: Operations to perform:
  Synchronize unmigrated apps: crispy_forms
  Apply all migrations: task_manager, sessions, admin, crawl_space, auth, contenttypes, base
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  No migrations to apply.
The following content types are stale and need to be deleted:

    task_manager | crawltask

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

- I think we need to pass some sort of force option so it doesn't prompt stdin like this.

**Comment by amfarrell** [comment]
It doesn't look like `manage.py migrate` has a force option. However we can do `yes "yes" | python mange.py migrate`

**Comment by ahmadia** [comment]
that's fine.
