### ISSUE TITLE
explorer.continuum.io leaves all ports open.

### ISSUE THREAD

**Issue by amfarrell** [memex-explorer/memex-explorer#605]
[ ] create a security group for memex-explorer-dev
[ ] modify ec2 startup script to use that security group.

**Comment by amfarrell** [comment]
This is completed in branch https://github.com/memex-explorer/memex-explorer/pull/606
@ahmadia thoughts on merging?

**Comment by ahmadia** [comment]
+1

**Comment by ahmadia** [comment]
In the future, security issues should NOT be reported in the public repository until they've been fixed.
