### ISSUE TITLE
Upgrade ache to 0.3.0

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#612]

**Comment by ahmadia** [comment]
PR is in: https://github.com/memex-explorer/memex-explorer/pull/621

**Comment by ahmadia** [comment]
This is working for me.  Any objection to merging @brittainhard?

**Comment by brittainhard** [comment]
Gonna test it out real quickly.

**Comment by brittainhard** [comment]
It works! This is awesome. +1
