### ISSUE TITLE
Add progress bar to Crawl Model uploader

### ISSUE THREAD

**Issue by rtapella** [memex-explorer/memex-explorer#630]
Crawl models can be large. Should be some sort of progress meter for these (especially for choppy or slower connections).

**Comment by ahmadia** [comment]
Agreed, we already have a progress indicator for uploading data, so it shouldn't be hard to add something similar for crawl models.  @brittainhard, what do you think?

**Comment by brittainhard** [comment]
Having a progress bar requires that the crawl model creation be an XMLHttpRequest, like add dataset. This will require converting the form to an async upload, but I was going to do that anyway @ahmadia
