### ISSUE TITLE
Project page shows Crawl as "STARTED" when it's really "STOPPED"

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#651]
Steps to reproduce:

* Start an ACHE crawl
* Stop the ACHE crawl
* visit the project page

(seen on FireFox)

**Comment by brittainhard** [comment]
Did refreshing the page not work?

**Comment by ahmadia** [comment]
That "fixes" it, but we're not correctly providing this content if the browser is caching that status.

**Comment by ahmadia** [comment]
Okay, I'm going to close this, I can't reproduce it.
