### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shikhagu** [memex-explorer/memex-explorer#679]
I downloaded the memex code and ran commands as documented in Readme. When I ran "./app_setup.sh", it gave me an error. The following extract is from npm-depub.logs:

10929 verbose pkgid contextify@0.1.14
10930 verbose cwd /Users/Dreams/Desktop/CSCI572-Assign1/memex-explorer-master/source
10931 error Darwin 14.5.0
10932 error argv "/Users/Dreams/anaconda/envs/memex/bin/node" "/Users/Dreams/anaconda/envs/memex/bin/npm" "install" "-g" "log.io"
10933 error node v4.1.0
10934 error npm  v2.14.3
10935 error code ELIFECYCLE
10936 error contextify@0.1.14 install: `node-gyp rebuild`
10936 error Exit status 1
10937 error Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
10937 error This is most likely a problem with the contextify package,
10937 error not with npm itself.
10937 error Tell the author that this fails on your system:
10937 error     node-gyp rebuild
10937 error You can get their info via:
10937 error     npm owner ls contextify
10937 error There is likely additional logging output above.
10938 verbose exit [ 1, true ]
10939 verbose unbuild lib/node_modules/log.io/node_modules/jquery/node_modules/contextify
10940 info preuninstall contextify@0.1.14
10941 info uninstall contextify@0.1.14

Also in the window where I ran the command it gave following error:

Traceback (most recent call last):
  File "logio_settings.py", line 22, in <module>
    f = open(os.path.join(os.environ["HOME"], ".log.io", "harvester.conf"), "w")
IOError: [Errno 2] No such file or directory: '/Users/Dreams/.log.io/harvester.conf'
~/Desktop/CSCI572-Assign1/memex-explorer-master/source
discarding /Users/Dreams/anaconda/envs/memex/bin from PATH

Please suggest what should be my next steps.

**Comment by ahmadia** [comment]
Hi @shikhagu.  The error you're receiving refers to a failed log.io installation.  log.io is the last component we install and is not required to successfully run Memex Explorer.  Can you go ahead and try the next steps in the README:

```
source activate memex
# in the memex-explorer/source directory
$ supervisord
```

And report back?

Thanks!

**Comment by shikhagu** [comment]
Ok awesome. I ran next commands and opened http://localhost:8000. I am seeing the Memex explorer screen. So I guess installation went perfect. Thanks.
