### ISSUE TITLE
Failed to install on mac

### ISSUE THREAD

**Issue by rrgirish** [memex-explorer/memex-explorer#683]
On running
./app_setup.sh
it runs for quite a while and then fails:
 define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsu...
                                                            ^
14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rrgirish/anaconda/envs/memex/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/rrgirish/anaconda/envs/memex/bin/node" "/Users/rrgirish/anaconda/envs/memex/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rrgirish/anaconda/envs/memex/lib/node_modules/log.io/node_modules/jquery/node_modules/contextify
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> ws@0.4.32 install /Users/rrgirish/anaconda/envs/memex/lib/node_modules/log.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> ws@0.4.32 install /Users/rrgirish/anaconda/envs/memex/lib/node_modules/log.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/rrgirish/anaconda/envs/memex/bin/node" "/Users/rrgirish/anaconda/envs/memex/bin/npm" "install" "-g" "log.io"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rrgirish/Documents/CSCI_572/memex-explorer/source/npm-debug.log
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rrgirish/anaconda/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/rrgirish/anaconda/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/Users/rrgirish/anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/Users/rrgirish/anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/rrgirish/anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'memex.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named celery
~/Documents/CSCI_572/memex-explorer/deploy ~/Documents/CSCI_572/memex-explorer/source

Any pointers for this?

**Comment by ahmadia** [comment]
Did you run `source activate memex` before the `supervisord` command?

**Comment by ahmadia** [comment]
@brittainhard / @chrismattmann / @kriehl  - I think I'd like to disable log.io from the default build.  Installing is too fragile and we keep hitting the same issues.  Any objections?

**Comment by rrgirish** [comment]
@ahmadia I never got to that step. I get this on running app_setup.sh

**Comment by ahmadia** [comment]
@rrgirish - Go ahead and run `source activate memex` then `supervisord`, the failed log.io install step shouldn't affect the rest of the application.

**Comment by rrgirish** [comment]
@ahmadia i ran supervisord but django and celery keep exiting. Memex is also not running on port 8000.
This is what i see on the console repeatedly:
2015-10-03 16:37:33,189 INFO spawned: 'django' with pid 15056
2015-10-03 16:37:33,663 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-10-03 16:37:33,701 INFO exited: celery (exit status 1; not expected)
2015-10-03 16:37:33,886 INFO spawned: 'celery' with pid 15059
2015-10-03 16:37:34,269 INFO success: django entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-10-03 16:37:34,295 INFO exited: django (exit status 1; not expected)
2015-10-03 16:37:34,583 INFO spawned: 'django' with pid 15062

**Comment by ahmadia** [comment]
Logs are in resources/logs or you can try starting the applications
manually. Please post back with what you find.

On Saturday, October 3, 2015, rrgirish <notifications@github.com> wrote:

> @ahmadia <https://github.com/ahmadia> i ran supervisord but django and
> celery keep exiting. Memex is also not running on port 8000.
> This is what i see on the console repeatedly:
> 2015-10-03 16:37:33,189 INFO spawned: 'django' with pid 15056
> 2015-10-03 16:37:33,663 INFO success: celery entered RUNNING state,
> process has stayed up for > than 1 seconds (startsecs)
> 2015-10-03 16:37:33,701 INFO exited: celery (exit status 1; not expected)
> 2015-10-03 16:37:33,886 INFO spawned: 'celery' with pid 15059
> 2015-10-03 16:37:34,269 INFO success: django entered RUNNING state,
> process has stayed up for > than 1 seconds (startsecs)
> 2015-10-03 16:37:34,295 INFO exited: django (exit status 1; not expected)
> 2015-10-03 16:37:34,583 INFO spawned: 'django' with pid 15062
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/683#issuecomment-145299477>
> .
>


-- 
_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>

**Comment by rrgirish** [comment]
@ahmadia Thanks for the logs location! There were a couple of python packages not installed on the mac. After installing those packages and then running supervisord, i get the server up and running.

However, on opening localhost:8000 i get this error page:

no such table: base_project
Request Method:	GET
Request URL:	http://localhost:8000/
Django Version:	1.7.3
Exception Type:	OperationalError
Exception Value:	
no such table: base_project
Exception Location:	/Users/rrgirish/anaconda/envs/memex/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 485
Python Executable:	/Users/rrgirish/anaconda/envs/memex/bin/python

Am i missing anything else?

**Comment by ahmadia** [comment]
The SQLite file is created when you run app_setup, and the packages are
installed in the Conda env create command. Try rerunning each of the
commands from app setup in the right directory except for the npm install.

On Saturday, October 3, 2015, rrgirish <notifications@github.com> wrote:

> @ahmadia <https://github.com/ahmadia> Thanks for the logs location! There
> were a couple of python packages not installed on the mac. After installing
> those packages and then running supervisord, i get the server up and
> running.
>
> However, on opening localhost:8000 i get this error page:
>
> no such table: base_project
> Request Method: GET
> Request URL: http://localhost:8000/
> Django Version: 1.7.3
> Exception Type: OperationalError
> Exception Value:
>
> no such table: base_project
> Exception Location:
> /Users/rrgirish/anaconda/envs/memex/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py
> in execute, line 485
> Python Executable: /Users/rrgirish/anaconda/envs/memex/bin/python
>
> Am i missing anything else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/683#issuecomment-145303993>
> .
>


-- 
_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>

**Comment by rrgirish** [comment]
Thanks a lot! I commented out the part on lib io in the app_setup file and ran it again. Now it works.

**Comment by ahmadia** [comment]
Awesome!  @rrgirish - please report back with your experiences/issues.  I'm going to leave this issue open since I'd like to address the issue of the failing log.io installs.
