### ISSUE TITLE
Clicking the view button in crawls page shows popup "do you want this crawl to be deleted" on safari

### ISSUE THREAD

**Issue by rrgirish** [memex-explorer/memex-explorer#685]
Note that this happens only on safari. I tried this on chrome and it worked fine.

On clicking the view button on the crawls page, instead of going to the crawls page, it shows the popup that is supposed to come on clicking the delete button.

**Comment by ahmadia** [comment]
Thanks for the report, we really appreciate it!  Please let us know if you find any others like it.

**Comment by brittainhard** [comment]
That's really bizarre. I'll take a look into it right now.
