### ISSUE TITLE
Is there a way to modify the nutch regex filter in memex?

### ISSUE THREAD

**Issue by rrgirish** [memex-explorer/memex-explorer#687]
I wanted to include images in the crawl and remove the restriction on urls containing "?", both of which are not present by default in nutch-default.xml. Is there a way to verify this setting or change it?

**Comment by ahmadia** [comment]
Images are crawled by default in our configuration of butch. Use 'which
crawl' with the environment activated for installation root.

On Sunday, October 4, 2015, rrgirish <notifications@github.com> wrote:

> I wanted to include images in the crawl and remove the restriction on urls
> containing "?", both of which are not present by default in
> nutch-default.xml. Is there a way to verify this setting or change it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/687>.
>


-- 
_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>

**Comment by rrgirish** [comment]
I see in the documentation that there is a button to view images on the UI, but on my local, there is no UI button to see that. There is a dashboard button
<img width="683" alt="screen shot 2015-10-04 at 9 17 48 pm" src="https://cloud.githubusercontent.com/assets/6744183/10272990/cbb7157e-6add-11e5-8e8f-0db13e9b949b.png">

Also, since the http.io is not loaded, the bottom half of the page shows up blank saying no connection could be made to port 28778
<img width="671" alt="screen shot 2015-10-04 at 9 21 18 pm" src="https://cloud.githubusercontent.com/assets/6744183/10272993/e41eb95a-6add-11e5-96c8-fe0900d74d36.png">

**Comment by rrgirish** [comment]
Also i notice in the crawl logs that sites which are not part of the seed list are also getting crawled. In nutch i could use db.ignore.external.links to true in site_default.xml, can i do something similar here?

**Comment by ahmadia** [comment]
Do you understand what I meant about nutch root?  On my laptop:

```
zsh 8882  (git)-[master]-% which crawl
/Users/aahmadia/anaconda/envs/memex/bin/crawl
```

and...

```
zsh 8883  (git)-[master]-% ls /Users/aahmadia/anaconda/envs/memex/lib/nutch
bin     conf    lib     logs    plugins
```

You can edit the `conf` file just like any other nutch job.  Dumping the images can be done from the command line, I think it may be currently disabled in Nutch.

**Comment by rrgirish** [comment]
Thanks! I found the file.
