### ISSUE TITLE
Create a new nutch crawl with space in the name will show success on run without crawling any urls

### ISSUE THREAD

**Issue by rrgirish** [memex-explorer/memex-explorer#688]
If you create a new nutch crawl and give a space in the name, the crawl will not get triggered, It will simply show success and complete all rounds.
This is what you see in the logs:

JAVA_HOME is set to '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home'
~/anaconda/envs/memex/lib/nutch ~/Documents/memex-explorer/source
Usage: crawl [-i|--index] [-D "key=value"] <Seed Dir> <Crawl Dir> <Num Rounds>
	-i|--index	Indexes crawl results into a configured indexer
	-D		A Java property to pass to Nutch calls
	Seed Dir	Directory in which to look for a seeds file
	Crawl Dir	Directory where the crawl/link/segments dirs are saved
	Num Rounds	The number of rounds to run this crawl for

**Comment by ahmadia** [comment]
wow, yeah that's a big bug.
