### ISSUE TITLE
Getting images from the crawl

### ISSUE THREAD

**Issue by saloneerege** [memex-explorer/memex-explorer#714]
I am trying to crawl weapons images and since the nutch that memex uses has the mimetypes.txt to only accept text/html will I have to add images/* there so that it accepts all images as memex crawls through the seedlist ?

**Comment by ahmadia** [comment]
Hi @saloneerege.  That sounds right to me.  @chrismattmann - do you have some thoughts on this?

**Comment by chrismattmann** [comment]
correct
