### ISSUE TITLE
dump images and dump common crawl have been disabled

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#717]
intentionally?  does this need to be restored?  Does the REST API support either of these?

**Comment by ahmadia** [comment]
I see the view code is still enabled: https://github.com/memex-explorer/memex-explorer/blob/master/source/apps/crawl_space/views.py#L171-L181

However, the corresponding template code was disabled, and possibly the JS buttons as well?  Was this lost in the backbone upgrade?

**Comment by brittainhard** [comment]
I can re-integrate that today and ensure that it is working. Rest API has no interaction here. The crawl page doesn't have any backbone views on it right now.

**Comment by ahmadia** [comment]
I don't think we can re-enable it.  Neither of these are available under the REST API as far as I know.

**Comment by ahmadia** [comment]
And the REST API is a big PR, so we should focus on landing that before we start landing other PRs into the code base.

**Comment by ahmadia** [comment]
Getting this in before 0.4 is going to be a reach, but I'll put it in just in case everything else aligns :)

**Comment by ahmadia** [comment]
This relies on updates to the Nutch trunk from @sujen1412 so keeping him in the loop on this issue.

**Comment by sujen1412** [comment]
I have uploaded a initial patch to dump common crawl data - https://issues.apache.org/jira/browse/NUTCH-2152.

**Comment by sujen1412** [comment]
API discussion for the dump service started on https://issues.apache.org/jira/browse/NUTCH-2156. 
Design doc link - http://docs.apachenutchrestapi.apiary.io/#

**Comment by ahmadia** [comment]
I'm reviewing this and it's not clear to me what exactly we should be exposing here.  I mean, we can tell the Nutch server to dump the segment to the file system, but I don't think this is particularly useful to Memex Explorer right now since the Nutch server is no longer local.

**Comment by ahmadia** [comment]
I think there might be a similar conversation around the common crawl dump command.  Indeed it's useful to be able to send these to the file system (and then maybe retrieve them?) in the general case.  I'm not sure how this fits in with the current Memex Explorer dashboard.

**Comment by ahmadia** [comment]
After speaking with Katrina about this I'm going to go ahead and implement/test in the current state.  We can discuss where to go with this after the release.

**Comment by ahmadia** [comment]
@sujen1412 - is this patch safe to use with the pub/sub patch on the 1.11 release candidate?

**Comment by ahmadia** [comment]
```
curl -O https://issues.apache.org/jira/secure/attachment/12769190/NUTCH-2152.git.patch
patch -p1 < NUTCH-2152.git.patch
```

**Comment by ahmadia** [comment]
Just to avoid confusion from anybody else, there's a patch for dumping *common crawl*, proposed API/documentation for the old *dump* methods, and never the twain shall meet :)

**Comment by ahmadia** [comment]
@sujen1412 - this looks good.  Landed in our elasticnutch and nutch-python builds

**Comment by ahmadia** [comment]
see https://github.com/memex-explorer/memex-explorer/pull/720#issuecomment-152306316

**Comment by ahmadia** [comment]
Implemented in https://github.com/memex-explorer/memex-explorer/commit/8c07361807ff043af9326f4dd856ec1ebd387257
