### ISSUE TITLE
memex explorer no longer airgapped

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#719]
https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

is now being network-loaded.  It's not obvious what's requesting this yet.

**Comment by brittainhard** [comment]
@ahmadia where i thee code is this being called?

**Comment by ahmadia** [comment]
Front page and a couple of other places.  There's a chance it's due to a browser plugin, I couldn't find it anywhere in the memex explorer source but wanted to note it.

**Comment by brittainhard** [comment]
I figured it out. Django debug toolbar is calling it. Since we dont have the debug toolbar in production, this shouldn't be a problem.

**Comment by ahmadia** [comment]
+1 let's close.

_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>
