### ISSUE TITLE
document how to enable/run optional services such as DDT

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#724]
This is not obvious to new users.

**Comment by gpfreitas** [comment]
Had a problem starting DDT:

    (memex)0269-gpfreitas:source gpfreitas$ supervisorctl start ddt
    http://localhost:9001 refused connection

**Comment by ahmadia** [comment]
Supervisord not responding. Is it up?

On Tuesday, October 27, 2015, Guilherme Freitas <notifications@github.com>
wrote:

> Had a problem starting DDT:
>
> (memex)0269-gpfreitas:source gpfreitas$ supervisorctl start ddthttp://localhost:9001 refused connection
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/724#issuecomment-151551521>
> .
>


-- 
_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>

**Comment by gpfreitas** [comment]
It wasn't. Thanks! It started fine now. But I still can't find any difference in the UI. Maybe I'm missing something.

**Comment by ahmadia** [comment]
Testing locally

**Comment by ahmadia** [comment]
Verified locally, still needs documentation though :)

**Comment by ahmadia** [comment]
"Optional Integrations" would be a useful documentation page where we could discuss how to install, configure, and run DDT, TAD, DataWake, and Bokeh Server / RabbitMQ.

**Comment by ahmadia** [comment]
@brittainhard - Do we have an "Optional Integrations" section in the new documentation?  I like the Nutch Visualizations section, but maybe we need to say a few general words about how Django query supervisor to see what's running to show what to display, supervisor manages processes, how to run/test them outside of supervisord, and then how to change the configuration files to autostart those services, using the Nutch Visualizations as an example?  What do you think?

**Comment by brittainhard** [comment]
I can add this in pretty quickly.

**Comment by ahmadia** [comment]
Fixed by Brittain in #765
