### ISSUE TITLE
Documentation - how to run RMQ

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#725]
* Install / update homebrew
* `brew install rabbitmq`
* `export PATH=/usr/local/sbin:$PATH`

**Comment by ahmadia** [comment]
cc @brittainhard

**Comment by brittainhard** [comment]
@ahmadia after updating homebrew and removing `export PATH=/usr/local/sbin:$PATH` from `~/.bash_profile` I had no issues starting rabbitmq. I think adding sbin to the path is maybe a troubleshooting move rather than a requirement, IMO.

**Comment by brittainhard** [comment]
also, I uninstalled and reinstalled rabbitmq

**Comment by ahmadia** [comment]
Type `which rabbitmq-server` at your command line.  You'll see it comes from `/usr/local/sbin`.

I looked at my system, and here are the contents of `/etc/paths`:

```
zsh 11806  (git)-[ahmadia/nutch-rest-refactor]-% cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

`/usr/local/sbin` was already on my path, maybe it was on yours as well?  This is workaround documentation anyway, so it doesn't need to be perfect :)

**Comment by brittainhard** [comment]
yeah you definitley need to add `/usr/local/sbin` to your path, I take back my previous comments.

**Comment by ahmadia** [comment]
Then edit supervisord.conf with the following change:

```
 [program:rabbitmq]
 command=rabbitmq-server
 priority=1
-autostart=false
+autostart=true

 [program:bokeh-server]
 command=bokeh-server --backend memory --port 5006
 priority=1
-autostart=false
+autostart=true

 [program:tika]
 command=tika-rest-server
```

**Comment by ahmadia** [comment]
And `rabbitmq-server` becomes `sudo rabbitmq-server` on Linux.

**Comment by ahmadia** [comment]
This is almost ready to close, I'm going to just directly edit the docs on master.

**Comment by ahmadia** [comment]
done
