### ISSUE TITLE
reenable job control

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#729]

**Comment by ahmadia** [comment]
easy but needs a quick discussion with Brittain.

**Comment by brittainhard** [comment]
This is the stop / force_stop functionality?

**Comment by ahmadia** [comment]
Yeah, I think a "stop" button is enough.  Nutch has some concept of "force kills/stops" on jobs but I think it's fine just to not feed it any more tasks after the current job the way we were doing before.  Except now we can just stop calling update from our side instead of fooling around with a stop file :)

**Comment by brittainhard** [comment]
ok. how does this work? are we still running crawls one round after another?

**Comment by ahmadia** [comment]
see https://github.com/memex-explorer/memex-explorer/blob/ahmadia/nutch-rest-refactor/source/task_manager/crawl_tasks.py#L39-L56

**Comment by ahmadia** [comment]
We basically need to reload the crawl model there in that while loop to check to see if we've received a kill message, if I understand how the job control is supposed to work.

**Comment by ahmadia** [comment]
I have to look through the source, I'm not sure where we were putting that stop file in, I only see it being removed in the PR diffs.

**Comment by brittainhard** [comment]
I had A LOT of trouble getting Celery to reload the Crawl object. I ended up using the stopfile because I couldn't find a way to reliably reload the Crawl object. I would recommend that you stick with it, and just copy the old code over.

I spent hours trying to figure it out and the stopfile was the only solution that worked.

**Comment by ahmadia** [comment]
Oh, I understand.  We should figure out what's going on there.  It can wait until after we land the PR.

**Comment by brittainhard** [comment]
This is the old stopfile code: https://github.com/memex-explorer/memex-explorer/blob/master/source/task_manager/crawl_tasks.py#L73-L77

The stopfile is created by the django view here: https://github.com/memex-explorer/memex-explorer/blob/master/source/apps/crawl_space/views.py#L161-L165

**Comment by ahmadia** [comment]
Yup, it looks like something that was handled better in Django 1.8, but we can try this http://stackoverflow.com/a/4874091/122022 since we don't have multiple references floating around and the object id is immutable.

**Comment by brittainhard** [comment]
Fell free to take another stab at it, I would love to see a fix to that stupid stopfile thing.
