### ISSUE TITLE
simultaneous crawl visualization

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#733]
In order to monitor the progress of multiple crawls simultaneously, we need to use the new features in development by @sujen1412 as part of follow-on work for https://issues.apache.org/jira/browse/NUTCH-2132

**Comment by ahmadia** [comment]
0.4 is going to be a reach, but I'd like to try for it.

**Comment by brittainhard** [comment]
so currently you can only visualize one crawl?

**Comment by ahmadia** [comment]
Well, you can visualize two crawls (or more), but the URLs would be mixed :)

**Comment by ahmadia** [comment]
Should be fixed in https://github.com/memex-explorer/memex-explorer/commit/c794a15a20a97f859e29e6e95eb1ea02ca6762ea

**Comment by ahmadia** [comment]
amended to https://github.com/memex-explorer/memex-explorer/commit/1a718dfda6930b20302c8e34b86df5e30c05a469
