### ISSUE TITLE
installation guide - can't upgrade existing databases

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#754]
Instruct users to manually remove `db.sqlite3` if installing from an older version of Memex Explorer, as migrations are not supported.

**Comment by brittainhard** [comment]
I think we can fix this by tracking migrations beyond 0001. I'll look into it later.

**Comment by brittainhard** [comment]
@ahmadia i think for this all we have to is just start tracking migration scripts beyond 0001. It wouldnt be necessary to add it to the docs, I don't think.

**Comment by ahmadia** [comment]
Do you want to go through and generate migration scripts for the previous releases or do you want to just start allowing migration from 0.4?

**Comment by brittainhard** [comment]
Grandfathering in migrations seems like a huge headache. I think we should just change this behavior going forward. All that is necessary is to change the .gitignore file to allow tracking migrations.

We may encounter problems if we are both modifying the Django models, but I feel like we can deal with those issues when they come up.

**Comment by ahmadia** [comment]
That's fine, I'll let you handle migrations.  We still need a note in the documents for people coming from a pre-0.4 release, since we don't promise migrations up to 0.4.

**Comment by brittainhard** [comment]
Fair enough. I'll add this in a PR.
