### ISSUE TITLE
Developers Not Working/Roanoke like condition. To replicate issue, build something amazing then unexpectedly stop.

### ISSUE THREAD

**Issue by SKGrimes** [memex-explorer/memex-explorer#770]
Dear Devs,

As a total stranger writing you a completely unsolicited issue I fully expect your undivided attentioin for the next 1.337 minutes here. I obviously don't have to tell you that using DNS, a browser, email, CDN, search engine, SSL cert, SSL implementation, messaging, docs, servers and basically the laymans definition of the whole bloody internet run by a single entity is just anti-intellectual baseline insanity or a completely convincing troll by the entire world. I mean, it is sort of like expecting some huge organization to build roads, infrastructure, protect you, prosecute you, represent you and organize everything in your daily life, right? Insane.

So about a year ago I realized that someone quite a bit more clever than myself probably also realized a private search engine would be pretty fucking useful, and super inevitable. You could just wire up the Apache ecosystem, Elastic, and like DNS-crypt and interface it with electron or docker and have your own ecosystem. Solve privacy, content payment and lack of innovation in a go. If anyone missed the subtle lockdown of websites by crawl blockers like distilli, the problems with content discovery and the lack of options or customization in search, they probably at least noticed that it feels pretty much like 1993 outside.
- Silicon Valley darling acquired a defunct games company that built a communication platform after its MMORPG failed, feels a bit like slack.
- Yahoo still exists, and it still doesn't get it.
- Evan Williams started his 3rd blog company.
- Kozmo is doing ridesharing and just in time delivery, with a recent logo redisign that made AirBnBs look like painting the sistine chapel, both grounded and elevated really.
- Bubbles, volatility, etc.
- It should be noted in this bizarre counterfactual analogy I made up, it is sort of difficult to ascertain where we are if we use apple as a measuring stick, it is super unclear if we are in the NeXT timeline or what. Like their software is totally shit, but they are knocking the ball out of the park financially. They just relaunched a music store and a new device, but no one needed a watch that lasts 24 hours to read texts. However, in reality 'Jobs' in this absurd timeline, is probably whoever is actually reading this, because this is the ipod, "controlling the internet and keeping it in your pocket".

Anyway, it's pretty fucking obvious a browser/search war is coming, as the next logical step in our 1993 groundhog day like experience.  

 Since the market potential is like $75 billion I figured I would hear about it, because it is pretty much analogous to the discovery that everyone in North America didn't need to watch Saved by The Bell at 8:00pm on Tuesdsay(9pm central).Which was a pretty big revelation for media companies, and all of the people mining magnetic tape in the VCRcoin ecosystem. I have been hopeful that someone else would start working on this and I could start using the product and at least try and find some smart developers to drive to the ecosystem. So when I found this project-- following nearly the same plan I had mapped out in my head, and saw 829 commits and hundreds of thousand lines of code, AND realized it was abandoned, alarm bells went off. 

I sort of couldn't imagine a scenario where this project gets sunsetted. I mean, Albino Blacksheep is still on the web and this ins't exactly a google acquihire auto-kill, so what is the deal? Is it money, time? Is it a canary?

Maybe I overlooked how the pinnacle achievement of our time is actually going to be using an interpreter that supports 20 years worth of syntax to manipulate a 1960s document publishing language, putting events in, then adding meta tags to what are already essentially fucking meta tags, and then taking this interpreter AND PUTTING IT ON BOTH SIDES OF THE STACK.

but I can't imagine that, so why did memex go Robin Williams here, it just makes no sense?

to close issue continue working on project.

**Comment by britthard** [comment]
This application is completely open source. You are free to fork the project and make any changes you wish to make if you want to contribute to the project. Please review our license for info about reusing this code. https://github.com/memex-explorer/memex-explorer/blob/master/LICENSE
